### ISSUE TITLE
The end of the world.

### ISSUE THREAD

**Issue by PablotTheOni** [KitaenSilva/KeplerObservatory#3]
Well, this now seems to work.
![mjqylpn](https://cloud.githubusercontent.com/assets/18729703/14906191/ec997b28-0db8-11e6-9896-f6dadc8e7a8e.gif)
Testing file attaching as well

**Comment by KitaenSilva** [comment]
bleep bloop test comment

**Comment by PablotTheOni** [comment]
Bleep bloop indeed!

**Comment by PablotTheOni** [comment]
issueception
